name: Test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Tests
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
        run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm ci
      - run: npm run build
      - run: npm test
